### PR TITLE
Basic Documentation of Plugin Limitations

### PR DESCRIPTION
**Pull request by Manuzor**
I've created a couple of examples to show-case some known limitations of this plugin.

I hope you find this useful.

### CODE REVIEW

**Comment by veelo** [comment]
Thanks for your contribution, Manuel. I will have a closer look later. On first glance, limitations depend on certain options being passed to the compiler, am I right? Would the linter work correctly if these options were passed to dmd by the linter? If so, I think we should try to pass these options. I take it you are aware of `"args"`, see https://github.com/veelo/SublimeLinter-contrib-dmd#settings?

Apropos limitations, there is also this: https://github.com/veelo/SublimeLinter-contrib-dmd/issues/2

**Comment by veelo** [comment]
A quick note: I am not sure it is worth your time to try and make the tests pass. These tests are imposed by the Sublime folks, and apply to the linter plugin itself. Your subdirectory though is not essential to the workings of the linter, and needn't be distributed with every linter installation. It is good to have these things documented, but I am not convinced that a subdirectory is the right place. I'll have to look into this.

**Comment by Manuzor** [comment]
Yea it's true, the samples I provide will work if you specify the linter args directly. Made me realize the PR in its current state is kind of useless then... 😅

Given that this plugin already makes use of dub describe, I jumped to the conclusion that stuff like `-J=.` should work automatically.

Closing this PR.

**Comment by veelo** [comment]
> stuff like `-J=.` should work automatically.

Correct. Feel free to open a PR against `readme.md` if you think the documentation can be improved.

**Pull request closed without merging**
